type_title: Kafka泛洪故障
type_plain: Kafka泛洪故障
flag_dsp_map:
  host:
    dsp: kafka服务器的主机地址
    must: false
  password:
    dsp: kafka 客户端密码
    must: false
  port:
    dsp: kafka 服务端口
    must: false
  size:
    dsp: 每个传输包的大小
    must: false
  threads:
    dsp: 工作线程数
    must: false
  username:
    dsp: kafka 客户端用户名
    must: false
