type_title: ""
type_plain: ""
flag_dsp_map:
  dns-domain-name:
    dsp: map this host to specified IP
    must: false
  dns-ip:
    dsp: map specified host to this IP address
    must: false
  dns-server:
    dsp: update the DNS server in /etc/resolv.conf with this value
    must: false
