type_title: ""
type_plain: ""
flag_dsp_map:
  addr:
    dsp: The address of redis server
    must: false
  password:
    dsp: The password of server
    must: false
  percent:
    dsp: The percentage of maxmemory
    must: false
  size:
    dsp: The size of cache
    must: false
